---
language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
env:
  - DJANGO="Django>1.10,<1.11"
  - DJANGO="Django>1.11,<2.0"
  - DJANGO="Django>2.0,<2.1"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"
exclude:
  # Django 2.0+ dropped support for Python 2.
  - python: "2.7"
    env: DJANGO="Django>=2.0,<2.1"
  - python: "3.4"
    env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install mock; fi
  - pip install -U pip
  - pip install coverage $DJANGO
script:
  - coverage run --source=./impersonate_auth ./runtests.py
